branchName: 'config-read-${scope}-${issue.number}-${issue.title}'
variables:
  - name: scope
    source: title
    # Questa regex cerca qualsiasi cosa dentro le quadre, ovunque siano nel titolo
    regex: '\[(.+?)\]' 
silent: false # IMPORTANTE: mettilo a false per vedere il debug nei log