branchName: '${scope}-${issue.number}-${issue.title}'
variables:
  - name: scope
    source: title
    # La parte (?<scope>...) dice esplicitamente: "Metti questo match in scope"
    regex: '\[(?<scope>.+?)\]'
    defaultValue: 'no-scope'
silent: false